import Vue from "vue";
import { Tabbar, TabItem,DatetimePicker,Toast,Popup,Picker,Field,Header,Button,Badge} from 'mint-ui';
Vue.component(Tabbar.name, Tabbar);
Vue.component(TabItem.name, TabItem);
Vue.component(DatetimePicker.name, DatetimePicker);
Vue.component(Toast.name, Toast);
Vue.component(Popup.name, Popup);
Vue.component(Picker.name, Picker);
Vue.component(Field.name, Field);
Vue.component(Header.name, Header);
Vue.component(Button.name, Button);
Vue.component(Badge.name, Badge);
